name: windows
on:
  push
  
jobs:
  build-test:
    name: Build the project on windows platform with Qt5
    runs-on: windows-2019
    strategy:
      matrix:
        include:
          #- qt_version: 5.6.3
          #  qt_target: desktop
          #  qt_arch: win64_msvc2015_64
          #- qt_version: 5.9.9
          #  qt_target: desktop
          #  qt_arch: win64_msvc2017_64
          #- qt_version: 5.12.9
          #  qt_target: desktop
          #  qt_arch: win64_msvc2017_64
          #  msvc_version: 2017
          - qt_version: 5.15.1
            qt_target: desktop
            qt_arch: win64_msvc2019_64
    steps:
      - name: cacheQt
        id: WindowsCacheQt
        uses: actions/cache@v1
        with:
          path: ../Qt/${{matrix.qt_ver}}/${{matrix.qt_arch}}
          key: ${{ runner.os }}-Qt/${{matrix.qt_version}}/${{matrix.qt_arch}} 
      # Install Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.10.0
        with:
          # Version of Qt to install
          version: ${{ matrix.qt_version }}
          # Target platform for build
          target: ${{ matrix.qt_target }}
          # Architecture for Windows/Android
          arch: ${{ matrix.qt_arch }}
          cached: ${{steps.WindowsCacheQt.outputs.cache-hit }}
      
      # Pull code and checkout.
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      # Build the project
      - name: build-msvc
        shell: cmd
        env:
          vc_arch: ${{ matrix.msvc_arch }}
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
          qmake
          nmake
