name: ubuntu18.04
on: 
  push:

jobs:
  build-test:
    name: build with ubuntu 18.04 and qt5.9.5
    runs-on: ubuntu-18.04
    steps:
      - name: Update system
        id: UpdateSystem
        run: sudo apt-get update --fix-missing -y
      - name: Install g++
        id: InstallGxx
        run: sudo apt-get install gcc g++ -y
      - name: Install gl1
        id: Installgl1
        run: sudo apt-get install libgl1-mesa-dev -y
      - name: Install make
        id: installMake
        run: sudo apt-get install make -y
      - name: Install Qt
        id: InstallQt
        run: sudo apt-get install qt5-default libqt5charts5 libqt5charts5-dev libqt5websockets5 libqt5websockets5-dev libqt5serialport5 libqt5serialport5-dev -y
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build project
        id: BuildPorject
        run: qmake QtGitHubActiionDemo.pro && make

