name: build-android
on: 
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        #qt_arch: [android_x86, android_armv7, android_arm64_v8a]
        qt_arch: [android_armv7]
        qt_ver: [5.12.10]
        qt_target: [android]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.10.0
        with:
          # Version of Qt to install
          version: ${{ matrix.qt_ver }}
          # Target platform for build
          target: ${{ matrix.qt_target }}
          # Architecture for Windows/Android
          arch: ${{ matrix.qt_arch }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build android
        # https://doc.qt.io/qt-5/deployment-android.html
        run: |
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
          echo $ANDROID_HOME $ANDROID_HOME
          qmake
          make install INSTALL_ROOT="./release"
          ls
          echo $JAVA_HOME_8_X64 
          export PATH-=$JAVA_HOME_11_X64
          echo $PATH
          androiddeployqt --verbose --output release/ --input $(ls *.json) --android-platform android-29 --jdk $JAVA_HOME_8_X64 --gradle
          ls
          
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.qt_arch }}
          path: release
