name: build-android
on: 
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        #qt_arch: [android_x86, android_armv7, android_arm64_v8a]
        qt_arch: [android_armv7]
        qt_ver: [5.12.10]
        qt_target: [android]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.10.0
        with:
          # Version of Qt to install
          version: ${{ matrix.qt_ver }}
          # Target platform for build
          target: ${{ matrix.qt_target }}
          # Architecture for Windows/Android
          arch: ${{ matrix.qt_arch }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build android
        # https://doc.qt.io/qt-5/deployment-android.html
        run: |
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
          qmake
          make install "./"
          echo 'androiddeployqt --output android-build --input android-libAfcApiDemo.so-deployment-settings.json'
          androiddeployqt --output release/ --input $(ls *.json)
          ls
          
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.qt_arch }}
          path: release
