name: release-for-ubuntu
on: 
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-16.04
    steps:
      - name: Update system
        id: UpdateSystem
        run: sudo apt-get update --fix-missing -y
        
      - name: Install g++
        id: InstallGxx
        run: sudo apt-get install gcc g++ -y
        
      - name: Install gl1
        id: Installgl1
        run: sudo apt-get install libgl1-mesa-dev -y
        
      - name: Install make
        id: InstallMake
        run: sudo apt-get install make -y
      
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.11.1
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          version: 5.12.10
          target: desktop
      
      - name: Pull Repositories
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build Project
        run: |
          qmake
          make
          ls -l
